### ISSUE TITLE
How much free space should be available?

### ISSUE THREAD

**Issue by kikirizki** [xuancong84/install-PyTorch-on-Android#3]
Thanks for great works, I am super exciting about this project, but I just wondering how much space I need in order to compile PyTorch  on Android ?

**Comment by xuancong84** [comment]
Well, it depends on the version of PyTorch and the space is about the same as when you compile it on a PC without CUDA.

**Comment by kikirizki** [comment]
I want to follow this repo v1.4.1, I mean the space for Terminal emulator + Ubuntu + pytorch repository, cause I don't have much space left on my phone,
